# Generated by Django 6.0 on 2025-12-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloryapp', '0003_caloryintakemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloryintakemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
